using System;

namespace ChatService.Models;

/// <summary>
/// Represents a chat message in the system.
/// This class defines the structure of messages exchanged between users,
/// including content, timing, and user association.
/// </summary>
public class Message
{
    /// <summary>
    /// Unique identifier for the message.
    /// This ID is automatically generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Identifier of the user who sent the message.
    /// This field establishes the relationship between the message and its sender.
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Content of the message.
    /// This is the actual text content that was sent by the user.
    /// </summary>
    public required string Content { get; set; }

    /// <summary>
    /// Timestamp when the message was sent (UTC).
    /// This field is automatically set to the current UTC time when the message is created.
    /// </summary>
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Navigation property to the user who sent the message.
    /// This property enables lazy loading of the associated user data.
    /// </summary>
    public User? User { get; set; }
}